# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  base    = "."
  publish = "dist"
  command = "make build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "make build"
  [context.production.environment]
    ACCESS_TOKEN = "super secret"
